package org.backend.payment.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldNameConstants;
import org.backend.common.entity.AbstractAuditingEntity;
import org.backend.payment.enums.PaymentMethod;
import org.backend.payment.enums.PaymentProvider;
import org.backend.payment.enums.PaymentStatus;

/**
 * Database entity representing a recorded payment transaction.
 * Inherits audit fields (e.g., createdAt, updatedAt) from {@link AbstractAuditingEntity}.
 */
@Entity(name = "PaymentTransaction")
@Table(
    name = "payment_transaction",
        uniqueConstraints = {
        @UniqueConstraint(name = "uk_payment_transaction_payment_code", columnNames = "payment_code"),
        @UniqueConstraint(name = "uk_payment_transaction_idempotency_key", columnNames = "idempotency_key")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@FieldNameConstants
public class PaymentTransaction extends AbstractAuditingEntity<Long> {

    /**
     * Unique internal autogenerated database ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Unique business/transaction reference code.
     */
    @Column(name = "payment_code", nullable = false, unique = true, length = 64)
    private String paymentCode;

    /**
     * Associated order ID.
     */
    @Column(name = "order_id", nullable = false, length = 128)
    private String orderId;

    /**
     * ID of the user performing the payment.
     */
    @Column(name = "user_id", nullable = false, length = 128)
    private String userId;

    /**
     * Payment provider handling the transaction (e.g., STRIPE).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "provider", nullable = false, length = 20)
    private PaymentProvider provider;

    /**
     * Selected payment method (e.g., CARD, GOOGLE_PAY).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "method", nullable = false, length = 20)
    private PaymentMethod method;

    /**
     * Total amount charged.
     */
    @Column(name = "amount", nullable = false)
    private Long amount;

    /**
     * Currency code (e.g. "usd").
     */
    @Column(name = "currency", nullable = false, length = 10)
    private String currency;

    /**
     * Current status of the transaction (e.g., PENDING, SUCCESS).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private PaymentStatus status;

    /**
     * Stripe specific PaymentIntent identifier.
     */
    @Column(name = "stripe_payment_intent_id", length = 128)
    private String stripePaymentIntentId;

    /**
     * Client secret associated with Stripe PaymentIntent, used by frontend clients.
     */
    @Column(name = "stripe_client_secret", length = 255)
    private String stripeClientSecret;

    /**
     * JSON payload or request token containing additional metadata of the intent.
     */
    @Column(name = "request_token", columnDefinition = "TEXT")
    private String requestToken;

    /**
     * Idempotency key to guarantee safety on retry attempts.
     */
    @Column(name = "idempotency_key", nullable = false, unique = true, length = 128)
    private String idempotencyKey;

    /**
     * Error details/reason for transaction failure.
     */
    @Column(name = "failure_reason", length = 500)
    private String failureReason;
}

