server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
  servlet:
    context-path: /api

spring:

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB

  application:
    name: audiobook-api
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://52.76.108.218:3306/audio_book
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: fa71d57726140a7b7f9713c900ce79f1820fbdcb3f7bfa14a45c64ae31820c1c
    expiration: 86400000
    issuer: audio-book
storage:
  aws:
    access-key: AKIAZDTLQ2N4MGR7XXDN
    secret-key: 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
    region: ap-southeast-1
    bucket-name: audio-book-4
  max-file-size: 1073741824 # 1GB
  max-total-file-size: 2147483648 # 2GB
  allowed-document-extensions: pdf, doc, docx, xls, xlsx
  allowed-image-extensions: png, jpg, jpeg

payment:
  stripe:
    secret-key: sk_test_51TJEgmBNCJng1g5FXgF8kC9C73XpTsfVeP4qbbRqOuJURincI9S8vrysPhVjpLqd2mYfa9PUT4MA6KAzvAOUB2R800IuVxfOhY
    publishable-key: pk_test_51TJEgmBNCJng1g5FDkS0Tr0bSPlsgIuEifZksUsRHGWYeFfNjkukpnkIJjifouMw4keVd2W2ja1Ha4kpyU5Sanil00gPpoF2Wb
    webhook-secret: whsec_e8a42224efb3bd8ce4c63ab3f30b6a4844bc6d6d31a4855a2665abbebf269c6f
    success-url: http://localhost:3000/payment/success
    cancel-url: http://localhost:3000/payment/cancel
