server:
  port: 8080
  servlet:
    context-path: /api



spring:
  application:
    name: audiobook-api
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://47.128.254.199:3306/audio_book
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: fa71d57726140a7b7f9713c900ce79f1820fbdcb3f7bfa14a45c64ae31820c1c
    expiration: 86400000
    issuer: audio-book