server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:0.0.0.0}
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB

  application:
    name: audiobook-api
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/audio_book
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: daidq2809@gmail.com
    password: xrka dfmk bqzk liky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: fa71d57726140a7b7f9713c900ce79f1820fbdcb3f7bfa14a45c64ae31820c1c
    expiration: 86400000
    issuer: audio-book
storage:
  aws:
    access-key: AKIAZDTLQ2N4MGR7XXDN
    secret-key: 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
    region: ap-southeast-1
    bucket-name: audio-book-4
  max-file-size: 1073741824 # 1GB
  max-total-file-size: 2147483648 # 2GB
  allowed-document-extensions: pdf, doc, docx, xls, xlsx
  allowed-image-extensions: png, jpg, jpeg
payment:
  stripe:
    secret-key: sk_test_51TJwfQFmNKLpnSxIfFrlByqApRASl4KH551CFq9uzJYO211n8l36XfSWPo7MORd8Y95keWwnp6GS4XK1vomI5tGD005eJGkGI0
    publishable-key: pk_test_51TJwfQFmNKLpnSxIvNFuAYoO0fu82YG7Hrsh9T05ZIfA0kTjY166kuODtYEyS7zt6L2MkbuEIExPDY9mqeheoa9800mdqPXHjC
    webhook-secret: whsec_22754d4198e647eea6f0aee72821ae733aac0904fb0d44816993d9891243a508
    success-url: http://localhost:3000/payment/success
    cancel-url: http://localhost:3000/payment/cancel
